STUDENTS_AMOUNT = 225
GROUP_SIZE = 15
GROUP_AMOUNT = STUDENTS_AMOUNT // GROUP_SIZE


MAX_SCORES = (70, 80, 55)
MIN_SCORES = (20, 15, 25)
PRIORITY_COEFFICIENTS = (3, 4, 5)

MAXIMUM_POSSIBLE_SCORE = sum(PRIORITY_COEFFICIENTS)

SCORE_VECTOR_LENGTH = len(MAX_SCORES)

SCORES_DATA_FILENAME = 'scores.txt'
